version: '3.8'

services:
  finan_web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: finan_web
    restart: always
    env_file:
      - ../flask/.env.production
    networks:
      - finan_internal
    depends_on:
      - finan_db
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - finan_uploads:/app/static/uploads
      - finan_instance:/app/instance

  finan_db:
    image: postgres:15-alpine
    container_name: finan_db
    restart: always
    environment:
      POSTGRES_USER: finan_user
      POSTGRES_PASSWORD: 891783bc8ceb6811a58be4cca2bc499a
      POSTGRES_DB: finan_db
    volumes:
      - finan_db_data:/var/lib/postgresql/data
    networks:
      - finan_internal

networks:
  finan_internal:
    driver: bridge

volumes:
  finan_db_data:
  finan_uploads:
  finan_instance:
